version: "3"

services:
    poseidon-front:
        container_name: poseidon-front
        image: fepremazzi/poseidon-front
        ports:
            - 4201:4200
    poseidon-bff:
        container_name: poseidon-bff
        image: fepremazzi/poseidon-bff
        ports:
            - 8080:8080
